image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# tasks:
# - init: echo 'init script' # runs during prebuild
#   command: echo 'start script'

vscode:
  extensions:
    - redhat.java@0.57.0:IhAHbFLCVH6Nr8sy6OkPxg==
    - vscjava.vscode-java-debug@0.25.0:kzrHloDvSyL81jltUd00Eg==