image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# tasks:
# - init: echo 'init script' # runs during prebuild
#   command: echo 'start script'
vscode:
  extensions:
    - redhat.java@0.65.0:4JWCPw/OuJWB252LWz4qAA==
    - vscjava.vscode-java-test@0.24.1:adMLnibuhohxpDp7AmLe9g==
    - vscjava.vscode-java-debug@0.28.0:Px7heanEkDCIeofdn8y81Q==